"""Tests for scripts/run_lesson.py: batch38-42 lessons (vision/pointcloud/generative, parametrized)."""

import subprocess
import sys

import pytest

from _run_lesson_helpers import _repo_root


@pytest.mark.parametrize(
    ("track", "lesson", "train_module"),
    [
        ("vision", "lesson_60_synthetic_image_deraining", "tracks.vision.lesson_60_synthetic_image_deraining.train"),
        ("vision", "lesson_61_synthetic_image_retrieval", "tracks.vision.lesson_61_synthetic_image_retrieval.train"),
        ("vision", "lesson_62_synthetic_image_matching", "tracks.vision.lesson_62_synthetic_image_matching.train"),
        ("vision", "lesson_63_synthetic_image_stitching", "tracks.vision.lesson_63_synthetic_image_stitching.train"),
        (
            "vision",
            "lesson_64_synthetic_fine_grained_recognition",
            "tracks.vision.lesson_64_synthetic_fine_grained_recognition.train",
        ),
        (
            "vision",
            "lesson_65_synthetic_few_shot_recognition",
            "tracks.vision.lesson_65_synthetic_few_shot_recognition.train",
        ),
        (
            "vision",
            "lesson_66_synthetic_video_object_detection",
            "tracks.vision.lesson_66_synthetic_video_object_detection.train",
        ),
        (
            "vision",
            "lesson_67_synthetic_video_stabilization",
            "tracks.vision.lesson_67_synthetic_video_stabilization.train",
        ),
        (
            "vision",
            "lesson_68_synthetic_video_frame_interpolation",
            "tracks.vision.lesson_68_synthetic_video_frame_interpolation.train",
        ),
        (
            "vision",
            "lesson_69_synthetic_video_restoration",
            "tracks.vision.lesson_69_synthetic_video_restoration.train",
        ),
        (
            "vision",
            "lesson_70_synthetic_video_understanding",
            "tracks.vision.lesson_70_synthetic_video_understanding.train",
        ),
        (
            "vision",
            "lesson_71_synthetic_video_summarization",
            "tracks.vision.lesson_71_synthetic_video_summarization.train",
        ),
        (
            "vision",
            "lesson_72_synthetic_video_enhancement",
            "tracks.vision.lesson_72_synthetic_video_enhancement.train",
        ),
        (
            "vision",
            "lesson_73_synthetic_video_object_segmentation",
            "tracks.vision.lesson_73_synthetic_video_object_segmentation.train",
        ),
        (
            "vision",
            "lesson_74_synthetic_video_instance_segmentation",
            "tracks.vision.lesson_74_synthetic_video_instance_segmentation.train",
        ),
        (
            "vision",
            "lesson_75_synthetic_video_matting",
            "tracks.vision.lesson_75_synthetic_video_matting.train",
        ),
        (
            "vision",
            "lesson_76_synthetic_image_deweathering",
            "tracks.vision.lesson_76_synthetic_image_deweathering.train",
        ),
        (
            "vision",
            "lesson_77_synthetic_transparent_depth_estimation",
            "tracks.vision.lesson_77_synthetic_transparent_depth_estimation.train",
        ),
        (
            "vision",
            "lesson_78_synthetic_image_relighting",
            "tracks.vision.lesson_78_synthetic_image_relighting.train",
        ),
        (
            "vision",
            "lesson_79_synthetic_transparent_object_segmentation",
            "tracks.vision.lesson_79_synthetic_transparent_object_segmentation.train",
        ),
        (
            "vision",
            "lesson_80_synthetic_event_camera_understanding",
            "tracks.vision.lesson_80_synthetic_event_camera_understanding.train",
        ),
        (
            "vision",
            "lesson_81_synthetic_shadow_detection",
            "tracks.vision.lesson_81_synthetic_shadow_detection.train",
        ),
        (
            "vision",
            "lesson_82_synthetic_layout_generation",
            "tracks.vision.lesson_82_synthetic_layout_generation.train",
        ),
        (
            "vision",
            "lesson_83_synthetic_panoptic_segmentation",
            "tracks.vision.lesson_83_synthetic_panoptic_segmentation.train",
        ),
        (
            "vision",
            "lesson_84_synthetic_medical_segmentation",
            "tracks.vision.lesson_84_synthetic_medical_segmentation.train",
        ),
        (
            "vision",
            "lesson_85_synthetic_scene_text_spotting",
            "tracks.vision.lesson_85_synthetic_scene_text_spotting.train",
        ),
        (
            "vision",
            "lesson_86_synthetic_co_segmentation",
            "tracks.vision.lesson_86_synthetic_co_segmentation.train",
        ),
        (
            "vision",
            "lesson_87_synthetic_action_recognition",
            "tracks.vision.lesson_87_synthetic_action_recognition.train",
        ),
        (
            "vision",
            "lesson_88_synthetic_reid",
            "tracks.vision.lesson_88_synthetic_reid.train",
        ),
        (
            "vision",
            "lesson_89_synthetic_anomaly_detection",
            "tracks.vision.lesson_89_synthetic_anomaly_detection.train",
        ),
        (
            "pointcloud",
            "lesson_24_compact_pointcloud_completion",
            "tracks.pointcloud.lesson_24_compact_pointcloud_completion.train",
        ),
        (
            "pointcloud",
            "lesson_25_compact_scene_flow_estimation",
            "tracks.pointcloud.lesson_25_compact_scene_flow_estimation.train",
        ),
        (
            "pointcloud",
            "lesson_26_compact_gaussian_splatting",
            "tracks.pointcloud.lesson_26_compact_gaussian_splatting.train",
        ),
        (
            "pointcloud",
            "lesson_27_compact_3d_object_detection",
            "tracks.pointcloud.lesson_27_compact_3d_object_detection.train",
        ),
        (
            "pointcloud",
            "lesson_28_compact_3d_semantic_segmentation",
            "tracks.pointcloud.lesson_28_compact_3d_semantic_segmentation.train",
        ),
        (
            "pointcloud",
            "lesson_29_compact_3d_instance_segmentation",
            "tracks.pointcloud.lesson_29_compact_3d_instance_segmentation.train",
        ),
        (
            "pointcloud",
            "lesson_30_compact_3d_object_tracking",
            "tracks.pointcloud.lesson_30_compact_3d_object_tracking.train",
        ),
        (
            "pointcloud",
            "lesson_31_compact_open_vocabulary_3d",
            "tracks.pointcloud.lesson_31_compact_open_vocabulary_3d.train",
        ),
        (
            "pointcloud",
            "lesson_32_compact_pointcloud_forecasting",
            "tracks.pointcloud.lesson_32_compact_pointcloud_forecasting.train",
        ),
        (
            "pointcloud",
            "lesson_33_compact_pointcloud_anomaly_detection",
            "tracks.pointcloud.lesson_33_compact_pointcloud_anomaly_detection.train",
        ),
        (
            "pointcloud",
            "lesson_34_compact_pointcloud_upsampling",
            "tracks.pointcloud.lesson_34_compact_pointcloud_upsampling.train",
        ),
        (
            "pointcloud",
            "lesson_35_compact_shape_correspondence_3d",
            "tracks.pointcloud.lesson_35_compact_shape_correspondence_3d.train",
        ),
        (
            "pointcloud",
            "lesson_36_compact_pointcloud_registration",
            "tracks.pointcloud.lesson_36_compact_pointcloud_registration.train",
        ),
        (
            "generative",
            "lesson_45_compact_video_diffusion",
            "tracks.generative.lesson_45_compact_video_diffusion.train",
        ),
        (
            "generative",
            "lesson_46_compact_image_to_video_diffusion",
            "tracks.generative.lesson_46_compact_image_to_video_diffusion.train",
        ),
        (
            "generative",
            "lesson_47_compact_text_to_3d",
            "tracks.generative.lesson_47_compact_text_to_3d.train",
        ),
        (
            "generative",
            "lesson_48_compact_image_to_3d",
            "tracks.generative.lesson_48_compact_image_to_3d.train",
        ),
        (
            "generative",
            "lesson_49_compact_text_to_video",
            "tracks.generative.lesson_49_compact_text_to_video.train",
        ),
        (
            "generative",
            "lesson_50_compact_video_to_video",
            "tracks.generative.lesson_50_compact_video_to_video.train",
        ),
        (
            "generative",
            "lesson_51_compact_world_models",
            "tracks.generative.lesson_51_compact_world_models.train",
        ),
    ],
)
def test_run_lesson_dry_run_resolves_batch38_to_batch42_train_modules(
    track: str, lesson: str, train_module: str
) -> None:
    proc = subprocess.run(
        [sys.executable, "scripts/run_lesson.py", track, lesson, "--dry-run"],
        cwd=str(_repo_root()),
        check=False,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0
    assert train_module in proc.stdout
