import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

REGRESSION_IMPORTS = (
    "Llms",
    "Llms.llama",
    "Llms.bloom",
    "Llms.gpt_neox",
    "Llms.lora",
    "Llms.llama_adapter",
    "Llms.LLaMA",
    "Llms.BLOOM",
    "Llms.GPT_NeoX",
    "Llms.LoRA",
    "Llms.LLaMA_Adapter",
    "Llms.t5",
    "Llms.flan_t5",
    "Llms.ul2",
    "Llms.T5",
    "Llms.Flan_T5",
    "Llms.UL2",
    "Llms.ai_bubbles",
    "Llms.bard",
    "Llms.blip2",
    "Llms.blip",
    "Llms.flamingo",
    "Llms.minigpt4",
    "Llms.AI_Bubbles",
    "Llms.Bard",
    "Llms.BLIP2",
    "Llms.BLIP",
    "Llms.Flamingo",
    "Llms.MiniGPT4",
    "Llms.palm",
    "Llms.lamda",
    "Llms.megatron",
    "Llms.instructblip",
    "Llms.llm_survey",
    "Llms.llm_timeline",
    "Llms.PaLM",
    "Llms.LaMDA",
    "Llms.Megatron",
    "Llms.instructgpt",
    "Llms.InstructBLIP",
    "Llms.self_instruct",
    "Llms.pythia",
    "Llms.InstructGPT",
    "Llms.Self_Instruct",
    "Llms.Pythia",
    "Llms.anthropic",
    "Llms.imagen",
    "Llms.vilt",
    "Llms.chinchilla",
    "Llms.zero",
    "Llms.parameter_server",
    "Llms.fed",
    "Llms.helm",
    "Llms.openassistant",
    "Llms.oasst1",
    "Llms.pile",
    "Llms.prompt_engineering_guide",
    "Llms.red_pajama",
    "Llms.the_stack",
    "Llms.scienceqa",
    "Llms.dolly",
    "Llms.gpt4all",
    "Llms.segment_anything",
    "Llms.starcoder",
    "Llms.chain_of_thought",
    "Llms.gpt4all_j",
    "Llms.mtf",
    "Llms.gpipe",
    "Llms.pathways",
    "Llms.Anthropic",
    "Llms.Imagen",
    "Llms.ViLT",
    "Llms.Chinchilla",
    "Llms.ZeRO",
    "Llms.Parameter_Server",
    "Llms.FED",
    "Llms.HELM",
    "Llms.OpenAssistant",
    "Llms.OASST1",
    "Llms.Pile",
    "Llms.Prompt_Engineering_Guide",
    "Llms.RedPajama",
    "Llms.The_Stack",
    "Llms.ScienceQA",
    "Llms.Dolly",
    "Llms.GPT4All",
    "Llms.Segment_Anything",
    "Llms.StarCoder",
    "Llms.Chain_of_Thought",
    "Llms.GPT4All_J",
    "Llms.LLM_Survey",
    "Llms.LLM_Timeline",
    "Llms.MTF",
    "Llms.GPipe",
    "Llms.Pathways",
    "dlhub.device",
    "ml_algorithms.python.clustering",
    "ml_algorithms.python.adaboost",
    "ml_algorithms.python.discriminant_analysis",
    "ml_algorithms.python.gmm",
    "ml_algorithms.python.gradient_boosting",
    "ml_algorithms.python.hmm",
    "ml_algorithms.python.kmedoids",
    "ml_algorithms.python.kmeans",
    "ml_algorithms.python.knn",
    "ml_algorithms.python.ica",
    "ml_algorithms.python.linear_models",
    "ml_algorithms.python.isomap",
    "ml_algorithms.python.markov_chain",
    "ml_algorithms.python.mlp",
    "ml_algorithms.python.nmf",
    "ml_algorithms.python.naive_bayes",
    "ml_algorithms.python.ngram",
    "ml_algorithms.python.pca",
    "ml_algorithms.python.perceptron",
    "ml_algorithms.python.random_forest",
    "ml_algorithms.python.spectral_clustering",
    "ml_algorithms.python.svm",
    "tracks.gnn.datasets.cora",
    "tracks.gnn.datasets.karate",
    "tracks.gnn.lesson_04_cora_node_classification_gcn.train",
    "tracks.gnn.lesson_05_label_propagation_cora.train",
    "tracks.gnn.lesson_06_graphsage_cora.train",
    "tracks.gnn.lesson_07_sdne_karate_embedding.train",
    "tracks.gnn.lesson_08_line_karate_embedding.train",
    "tracks.gnn.lesson_09_metapath2vec_toy_hetero_embedding.train",
    "tracks.gnn.lesson_10_pinsage_toy_recommender.train",
    "tracks.gnn.lesson_11_rgcn_toy_node_classification.train",
)


@pytest.mark.parametrize("module_name", REGRESSION_IMPORTS)
def test_regression_modules_import_without_nameerror_or_bad_relative_imports(
    module_name: str,
) -> None:
    proc = subprocess.run(
        [sys.executable, "-c", f"import {module_name}"],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert proc.returncode == 0, (
        f"{module_name} failed to import.\n" f"stdout:\n{proc.stdout}\n" f"stderr:\n{proc.stderr}"
    )
